# Generated by Django 2.1.5 on 2019-01-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_classlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='tech_teacher',
            field=models.ManyToManyField(blank=True, related_name='tech_teacher', to='web.UserInfo', verbose_name='授课老师'),
        ),
    ]
