# Generated by Django 2.1.5 on 2019-01-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_consultrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultrecord',
            name='date',
        ),
    ]
